"""
https://leetcode.com/problems/find-the-difference/

You are given two strings s and t.

String t is generated by random shuffling string s and then add
one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
"""
def findTheDifference(s, t):
    """
    :type s: str
    :type t: str
    :rtype: str
    """
    ss = {}
    tt = {}
    for letter in s:
        if letter in ss:
            ss[letter] += 1
        else:
            ss[letter] = 1

    for letter in t:
        if letter in tt:
            tt[letter] += 1
        else:
            tt[letter] = 1

    for key in tt:
        if key not in ss or ss[key] != tt[key]:
            return key
        
